name: fmcg_pipeline
version: 1.0.0
config-version: 2

profile: fmcg_pipeline

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fmcg_pipeline:
    staging:
      +schema: staging
      +materialized: view
    gold:
      +schema: gold
      +materialized: table